### ISSUE TITLE
main.js

### ISSUE THREAD

**Issue by Gao996** [rejetto/hfs-aborted-see-new-repo#10]
![image](https://user-images.githubusercontent.com/51224634/143191624-d0e6cca1-9095-4b3b-b5bb-1f16ad117262.png)

```
GLOBAL.vfs = new vfsLib.Vfs();
```

This line of code seems to have.

**Comment by rejetto** [comment]
i don't understand the sense of this message

**Comment by Gao996** [comment]
> 我不明白这条消息的意义

It seems that I can't compile successfully with the old version of the library. I always report some type errors. Do you have the latest version of the library

**Comment by Gao996** [comment]
Oh, I'm talking about hfs2 package. Because HFS can't run, I use hfs2

**Comment by rejetto** [comment]
ok, i see you have switched to the other repository now, i'm closing this
