### ISSUE TITLE
How to upload files, do they support.

### ISSUE THREAD

**Issue by Gao996** [rejetto/hfs-aborted-see-new-repo#11]
Here you can use nodejs to write a tutorial, because nodejs has better concurrency, although there are not many functions, you can write a tutorial that only provides upload and download.

There is a small problem here. The "resource" here is always "undefined" or "null". How to deal with it here is that I am the only one who reported an error.
![image](https://user-images.githubusercontent.com/51224634/145319289-8dd1413d-8da3-4610-b803-09097f34b498.png)

**Comment by Gao996** [comment]
There is still a problem here, when downloading:
1. If the file name contains "#", then the page 404 will not be found.
2. If the file name contains Chinese, it will report an error and stop the service.

**Comment by rejetto** [comment]
moved to https://github.com/rejetto/hfs
