### ISSUE TITLE
ETA?

### ISSUE THREAD

**Issue by aolko** [rejetto/hfs-aborted-see-new-repo#3]
When it's going to be done?

**Comment by rejetto** [comment]
at this speed it's going to take forever -.-

**Comment by rejetto** [comment]
at this very moment i'm trying to make a big redesign, as i think i made a wrong choice in having administration and front-end totally separated

**Comment by aolko** [comment]
that's quite sad :(

**Comment by CanadianJeff** [comment]
sorry to hear its not going so well for you

**Comment by Schwarttzy** [comment]
Sorry to hear that, would really like to see this become a success

**Comment by jaZzKCS** [comment]
I have been using your websever for aeons it feels like. I would like to volunteer to help any way I can!

Keep up the good work!

**Comment by mhoney** [comment]
Really look forward to the next version!

**Comment by xpresservers** [comment]
@rejetto Any luck in this? :)

**Comment by KrasnayaPloshchad** [comment]
> at this very moment i'm trying to make a big redesign, as i think i made a wrong choice in having administration and front-end totally separated

On GitHub you can create a branch for this work, then everyone can give a help to you if you mentioned on README.md

**Comment by aolko** [comment]
alright, developer gave up, anyone to take on this?

**Comment by niceperson** [comment]
wow the last comment somehow surprises me. jun2017 eh..
i used to use hfs back in 2006/7.
only now 2018 i realised about this ver.3 attempt

**Comment by aolko** [comment]
well, person # 2 was right after all, people should do __something__ about it

**Comment by rejetto** [comment]
moved to https://github.com/rejetto/hfs
