### ISSUE TITLE
How to install and get it running

### ISSUE THREAD

**Issue by betonetotbo** [rejetto/hfs-aborted-see-new-repo#5]
Please create a guide about how to install and get it running.

**Comment by Wireless4024** [comment]
http://rejetto.com/wiki/index.php?title=HFS:_Introduction

**Comment by holoadmin** [comment]
@Wireless4024 the instruction from your link are for Version 2.3 from http://www.rejetto.com/hfs/ .
I'm also still wondering how to get this Version 3 running ...

**Comment by rejetto** [comment]
moved to https://github.com/rejetto/hfs
