### ISSUE TITLE
Chat for HFS

### ISSUE THREAD

**Issue by username1565** [rejetto/hfs-aborted-see-new-repo#7]
Hi. I can propose you to write simply javascript frontend to do chat.
I have the next idea.
1. Create folder with frontend there.
2. Make folder "Upload_messages" inside and make this uploadable for anyone.
3. Run HFS, and add frontend.
Any user, write message, and send this as FILE from his browser,
using POST query to uploadable folder.
Then, client-side script for this user checking files each by each for availablity,
and to get messages do download this files, using Web-sockets, XHR etc, in browser.
After that, chat-history is dowloaded and all previous messages available there.
This is JavaScript Live chat, and this can working in local network without Internet.

No need to create any chat-rooms or some channels,
no need third-party server,
no need register on any services,
no need to pay somewhat for someone.

I have working example of chat for Windows HFS.exe, but I cann't publish this on github.
This no make any sence, because I cann't create uploadable folder in github repositary.

This idea is better than PHP+MySQL/Node.js/Jabber_server and another server_side application,
with large proprietary code.
This chat can be realized using Javascript (+JQuery) only.
Just client-side frontend + HFS + uploadable folder.
Also, this can working in TOR-network, and maybe SSL, AES, RSA, Diffie-Hellman,
Elliptic-curves or NaCl encrypt/decrypt can be added.

Think about it. Maybe, this would enhance the level of effective communication on Earth.

Best regards, and have a nice day. =)

**Comment by rejetto** [comment]
hi, i guess you are talking about HFS version 2, that is not currently hosted here on github.
If you have any contribution like that you are welcome to publish it on the forum http://rejetto.com/forum/index.php?board=21.0

At the moment i'm not considering a chat feature in hfs itself, but such features should be provided as extra packages

**Comment by username1565** [comment]
Ok, I did post the code with working example here:
http://rejetto.com/forum/index.php?topic=12119.0 - HFS_FILE_CHAT_XHR.zip (129.74 kB)

But I think you can make this more elegant in server-side code.
Because each message there is saved in 1 file.
If number of messages will be over 1 million each user must to save every time this million files.
:-)

**Comment by rejetto** [comment]
moved to https://github.com/rejetto/hfs
